version: '3.3'
services:
    whoami:
        # container_name: whoami
        image: traefik/whoami
        security_opt:
            - no-new-privileges:true
        networks:
            - red
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.chat.localhost`)"
        - "traefik.http.routers.whoami.tls=true"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
    red:
      external: true