version: '3.3'
services:
  chatservice:
    # container_name: chatservice
    image: chatservice:v0.6.0

    networks:
      - red
    env_file:
      - .env
    restart: always

    #Configuracion Autoscaling de Traefik
    # deploy:
    #     replicas: 1

    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.chatservice.rule=Host(`${NAME}.localhost`)" # && PathPrefix(`/ws`)"
    - "traefik.http.routers.chatservice.tls=true"
    - "traefik.http.services.chatservice.loadbalancer.server.port=7000"
    - "traefik.http.routers.chatservice.entrypoints=http,https,redis,mysql,wss"
    - "traefik.http.services.chatservice.loadbalancer.sticky.cookie=true"

    #Configuracion Autoscaling de Traefik
    - "traefik.autoscale=true"

    #Circuit Breaker
    - "traefik.http.middlewares.chatservice-cb.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.10 || NetworkErrorRatio() > 0.10 || LatencyAtQuantileMS(50.0) > 100"
    
networks:
  red:
    external: true
